//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEncoding.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEncoding.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 待解码的字节数组的首位字节异常! 的本地化字符串。
        /// </summary>
        internal static string BytesFirstByteError {
            get {
                return ResourceManager.GetString("BytesFirstByteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待解码的字节数值长度过长! 的本地化字符串。
        /// </summary>
        internal static string BytesLengthTooLong {
            get {
                return ResourceManager.GetString("BytesLengthTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待解码的字节数值长度为零! 的本地化字符串。
        /// </summary>
        internal static string BytesLengthZero {
            get {
                return ResourceManager.GetString("BytesLengthZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B编码字节流的整数部分解析错误! 的本地化字符串。
        /// </summary>
        internal static string BytesNodeIntError {
            get {
                return ResourceManager.GetString("BytesNodeIntError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B编码字节流的字节数组长度异常! 的本地化字符串。
        /// </summary>
        internal static string BytesNodeLengthError {
            get {
                return ResourceManager.GetString("BytesNodeLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待添加的字符串关系字长度为0! 的本地化字符串。
        /// </summary>
        internal static string DictNodeKeyLengthError {
            get {
                return ResourceManager.GetString("DictNodeKeyLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B编码字典类的字节数组长度异常! 的本地化字符串。
        /// </summary>
        internal static string DictNodeLengthError {
            get {
                return ResourceManager.GetString("DictNodeLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B编码字典类中包含相同的字符串关键字! 的本地化字符串。
        /// </summary>
        internal static string DictNodeSameKey {
            get {
                return ResourceManager.GetString("DictNodeSameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待添加的B编码节点为空! 的本地化字符串。
        /// </summary>
        internal static string DictNodeValueIsNull {
            get {
                return ResourceManager.GetString("DictNodeValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B编码整数类的字节数组长度异常! 的本地化字符串。
        /// </summary>
        internal static string IntNodeLengthError {
            get {
                return ResourceManager.GetString("IntNodeLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B编码整数类的匹配错误! 的本地化字符串。
        /// </summary>
        internal static string IntNodeMatchError {
            get {
                return ResourceManager.GetString("IntNodeMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B编码列表类的字节数组长度异常! 的本地化字符串。
        /// </summary>
        internal static string ListNodeLengthError {
            get {
                return ResourceManager.GetString("ListNodeLengthError", resourceCulture);
            }
        }
    }
}
